name: s2connect
description: "A new Flutter project."

# pub.devに公開しない設定。公開する場合はこの行を削除してください。
publish_to: 'none'

# アプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は、ドットで区切られた3つの数字で構成されます。
# 例: 1.2.43 + 任意のビルド番号
# Androidでは、build-nameはversionNameとして使用され、build-numberはversionCodeとして使用されます。
# iOSでは、build-nameはCFBundleShortVersionStringとして、build-numberはCFBundleVersionとして使用されます。
# 詳細は以下のリンクを参照してください。
# Android: https://developer.android.com/studio/publish/versioning
# iOS: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertinoスタイルのアイコンを使用するための依存関係
  cupertino_icons: ^1.0.6

  # Firebase関連の依存関係
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3

  # ナビゲーションと状態管理のための依存関係
  go_router: ^14.2.6
  provider: ^6.0.5

  # 画像選択のための依存関係
  image_picker: ^1.1.2

  # アイテムの並び替えウィジェット
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # コーディング規約のリント設定
  flutter_lints: ^4.0.0

flutter:
  # Materialデザインを使用する設定
  uses-material-design: true

  # カスタムフォントの設定
  fonts:
    - family: Zen Maru Gothic
      fonts:
        - asset: fonts/ZenMaruGothic-Regular.ttf
        - asset: fonts/ZenMaruGothic-Bold.ttf
          weight: 700
        - asset: fonts/ZenMaruGothic-Light.ttf
          weight: 300
        - asset: fonts/ZenMaruGothic-Medium.ttf
          weight: 500
        - asset: fonts/ZenMaruGothic-Black.ttf
          weight: 900

  # アセット（画像など）の設定
  assets:
    - assets/images/S2.png
    - assets/images/S3.png
    - assets/images/kobato.png
  # 画像やフォントなど、他のアセットの追加のための設定例
  # これらのコメントはアセットを追加する際の参考として残されています。
  # 例:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # 解像度別のバリアント画像の指定方法についての参考情報
  # 詳細は以下のリンクを参照してください。
  # https://flutter.dev/assets-and-images/#resolution-aware

  # パッケージ依存のアセットを追加する方法についての参考情報
  # 詳細は以下のリンクを参照してください。
  # https://flutter.dev/assets-and-images/#from-packages

  # カスタムフォントの追加方法についての参考情報
  # 例:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存のフォントの詳細については、以下のリンクを参照してください。
  # https://flutter.dev/custom-fonts/#from-packages
