// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXAwDJG_Hb9TkeBGh6MH2zc2g3gom413A',
    appId: '1:459998986468:web:9f8d70c1e0221bcbb6acf1',
    messagingSenderId: '459998986468',
    projectId: 's2test-7adb2',
    authDomain: 's2test-7adb2.firebaseapp.com',
    storageBucket: 's2test-7adb2.appspot.com',
    measurementId: 'G-5RGZE6EEX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9oYW_z_It-Z_5hapUPZLSCCTZB8C_P_0',
    appId: '1:459998986468:android:1c2d6a4c6cb546f7b6acf1',
    messagingSenderId: '459998986468',
    projectId: 's2test-7adb2',
    storageBucket: 's2test-7adb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ8tFyYG5wupBhFV9Pc1xU-fu4aGCE-uo',
    appId: '1:459998986468:ios:f0398e67a8de2badb6acf1',
    messagingSenderId: '459998986468',
    projectId: 's2test-7adb2',
    storageBucket: 's2test-7adb2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ8tFyYG5wupBhFV9Pc1xU-fu4aGCE-uo',
    appId: '1:459998986468:ios:f0398e67a8de2badb6acf1',
    messagingSenderId: '459998986468',
    projectId: 's2test-7adb2',
    storageBucket: 's2test-7adb2.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXAwDJG_Hb9TkeBGh6MH2zc2g3gom413A',
    appId: '1:459998986468:web:3a2beb7369d49d18b6acf1',
    messagingSenderId: '459998986468',
    projectId: 's2test-7adb2',
    authDomain: 's2test-7adb2.firebaseapp.com',
    storageBucket: 's2test-7adb2.appspot.com',
    measurementId: 'G-E9F51D4WR4',
  );
}
